---
name: Build (master, multi-arch)
on:
  schedule:
    - cron: "0 23 1 * *"
  workflow_dispatch:
    inputs:
      git_sha:
        description: Override Emacs git commit SHA to build
        required: false

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      git_ref: master
      git_sha: ${{ github.event.inputs.git_sha }}
      builder_ref: "v0.6.43"
      os: macos-11
      x86_64: true
      arm64: true
    secrets:
      APPLE_DEVELOPER_CERTIFICATE_P12_BASE64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
      APPLE_DEVELOPER_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      AC_USERNAME: ${{ secrets.AC_USERNAME }}
      AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
      AC_PROVIDER: ${{ secrets.AC_PROVIDER }}
      AC_SIGN_IDENTITY: ${{ secrets.AC_SIGN_IDENTITY }}
      TAP_REPO_TOKEN: ${{ secrets.TAP_REPO_TOKEN }}
