---
name: Nightly (master)
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
    inputs:
      git_sha:
        description: Override Emacs git commit SHA to build
        required: false

jobs:
  build:
    name: Build
    uses: ./.github/workflows/_build.yml
    with:
      git_ref: "master"
      git_sha: ${{ inputs.git_sha }}
      builder_ref: "v0.6.54"
    secrets: inherit
