---
name: Update Metadata
concurrency: jimeh/emacs-builds/update-metadata
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout meta branch
        uses: actions/checkout@v3
        with:
          ref: meta
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: update total downloads shield JSON
        run: >-
          go run . badges downloads
          --output total-downloads/shield.json
          --cache total-downloads/.cache.json
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: commit and push changes to meta branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(meta): update metadata files"
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: >-
            github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          skip_dirty_check: false
